name: update-with-spacefinder-data
on: workflow_dispatch
jobs:
  update-pages:
    runs-on: ubuntu-latest
    name: Update pages from data file
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Update and commit
      run: | 
        cd main
        npm run build
        git config --global user.name 'peteredwards'
        git config --global user.email 'p.l.edwards@leeds.ac.uk'
        git add --all
        git diff-index --quiet HEAD || (git commit -am "[bot] Content updated with spacefinder data" && git push)